name = "JuliaSimulation"
uuid = "6039efdd-b72b-4046-9c68-94bfbe29acf9"
authors = ["yyasui"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
